### ISSUE TITLE
What does ['verify' => false] mean in $client = new Mosparo\ApiClient\Client() function

### ISSUE THREAD

**Issue by SuitDeer** [mosparo/php-api-client#2]
Hello,
I have a question.

What does the `['verify' => false]` mean in the function:
`$client = new Mosparo\ApiClient\Client($url, $publicKey, $privateKey, ['verify' => false]);`

**Comment by zepich** [comment]
Hi @SuitDeer 

The fourth client parameter is an array with the options for the Guzzle client. They are directly passed to the Guzzle Client object in line 220 (https://github.com/mosparo/php-api-client/blob/master/src/Client.php#L220).

With the `verify` option, you can disable the verification of the server's SSL certificate (https://docs.guzzlephp.org/en/stable/request-options.html#verify). This is useful if you host your mosparo installation on a host with a self-signed SSL certificate. In a production environment, you should not need `'verify' => false` usually since you should have a valid SSL certificate there.

Please let me know if that helps you or if you have other questions.

Kind regards,

zepich

**Comment by SuitDeer** [comment]
Thanks for the fast answer.

Perhaps your explanation of this parameter can be integrated into the README.md of this repository.
I was a little bit worried about this parameter.

**Comment by zepich** [comment]
Hi @SuitDeer 

Thank you very much for your suggestion.

Yes, I agree. I will update the example code and adjust the documentation.

Thank you very much for your help in making mosparo better!

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @SuitDeer 

I've updated the README.md. What do you think?

Kind regards,

zepich

**Comment by SuitDeer** [comment]
Hi @zepich, the new comments about the Guzzle arguments are good 👍

**Comment by SuitDeer** [comment]
Hi @zepich, the new comments about the Guzzle arguments are good 👍
